VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

LTO_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
AUTO_SHIFT_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
GRAVE_ESC_ENABLE = no

DEBOUNCE_TYPE = sym_eager_pk
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
