VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
VIALRGB_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
GRAVE_ESC_ENABLE = no

DEBOUNCE_TYPE = sym_eager_pk
